Site\MainBundle\Entity\Settings:
    properties:
        key:
            - NotBlank:
                message: "Ключ не может быть пустым"
        value:
            - NotBlank:
                message: "Значение не может быть пустым"

Site\MainBundle\Entity\Hotel:
    properties:
        name:
            - NotBlank:
                message: "Название отеля не может быть пустым"  

Site\MainBundle\Entity\Stations:
    properties:
        name:
            - NotBlank:
                message: "Название вокзала не может быть пустым"      

Site\MainBundle\Entity\ClassRoom:
    properties:
        name:
            - NotBlank:
                message: "Класс номера не может быть пустым"                                                                        