frontend_homepage:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/Main:index" }

frontend_register:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/register.yml"
    prefix:   /register