frontend_register_index:
    path:     /{register_date}
    defaults: { _controller: "SiteMainBundle:Frontend/Auth:registration" }

frontend_page_index:
    path:     /{register_date}/{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/Page:index" }